const $=s=>document.querySelector(s);let course=null,currentVideo=null,lastSave=0;
async function getJSON(u,o){const r=await fetch(u,o);if(!r.ok)throw new Error(await r.text());return r.json()}
async function load(){course=await getJSON('/api/course');renderActivities();renderConcepts();renderTimeline();initVideos();await refresh()}
async function refresh(){const s=await getJSON('/api/dashboard');$('#overall').textContent=(s.overall??0)+'%';$('#overallbar').style.width=(s.overall??0)+'%';$('#mastery').textContent=(s.mastery??0)+'%';$('#masterybar').style.width=(s.mastery??0)+'%';$('#evidence').textContent=s.evidence_count??0;$('#unknown').textContent=(s.unknown_count??0);renderCert(s.certificate)}
function renderCert(cert){if(!cert)return;const box=$('#certInfo');const btn=$('#certBtn');if(!btn)return;if(cert.issued){btn.style.display='none';box.innerHTML=`<div class="cert-ok">✅ Certificado emitido: <b>${esc(cert.certificate_id)}</b></div>`;$('#certLink').textContent='Verificar en línea →';$('#certLink').href='/verificar/'+encodeURIComponent(cert.certificate_id);}else{btn.style.display='inline-block';box.innerHTML=`<div class="cert-pending">Estado: <b>${esc(cert.status)}</b> · no emitido aún.</div>`;$('#certLink').textContent='Ver certificado →';$('#certLink').href='/certificado';}}
async function issueCert(){if(!confirm('¿Confirmas que completaste todas las evidencias del curso? El certificado se otorga UNA sola vez por curso.'))return;const btn=$('#certBtn');btn.disabled=true;btn.textContent='Evaluando…';try{const r=await getJSON('/api/certificate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_confirmation:true})});$('#certBox').innerHTML=`<div class="cert-ok">✅ ${esc(r.certificate_id)}<br><a href="${r.verification_url}" target="_blank">Verificar en línea</a></div>`;await refresh();}catch(e){let msg=e.message;try{msg=JSON.parse(e.message).error||e.message}catch(_){};$('#certInfo').innerHTML=`<div class="cert-err">⚠️ ${esc(msg)}</div>`;btn.disabled=false;btn.textContent='Emitir certificado';}}
function renderActivities(){const box=$('#activityList');box.innerHTML='';(course.items||[]).filter(x=>x.kind==='activity').forEach(x=>{const l=document.createElement('label');l.className='task';l.innerHTML=`<input type="checkbox"><span><b>${esc(x.title)}</b><small>${x.due?` · cierre ${x.due}`:''}</small></span>`;l.querySelector('input').addEventListener('change',async e=>{await getJSON('/api/item/'+x.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:e.target.checked})});refresh()});box.appendChild(l)})}
function renderConcepts(){const b=$('#conceptList');b.innerHTML='';(course.concepts||[]).forEach(x=>{const a=document.createElement('article');a.className='concept';a.innerHTML=`<strong>${esc(x.title)}</strong><p>${esc(x.definition)}</p>`;b.appendChild(a)})}
function renderTimeline(){const b=$('#timeline');b.innerHTML='';[['01','Fundamentos','Contenido y vocabulario base.'],['02','Activos y valoración','Componente formativo 1 · AA1.'],['03','Amenazas y riesgo','Componentes formativos siguientes.'],['04','Evidencias','Demostrar lo comprendido.']].forEach(([n,t,d])=>{const a=document.createElement('article');a.className='concept';a.innerHTML=`<strong>${n} · ${esc(t)}</strong><p>${esc(d)}</p>`;b.appendChild(a)})}
function initVideos(){const s=$('#videoSelect');s.innerHTML='<option value="">Selecciona una grabación…</option>';(course.videos||[]).forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.title;s.appendChild(o)});s.addEventListener('change',()=>selectVideo(s.value))}
async function selectVideo(id){if(!id)return;currentVideo=course.videos.find(x=>x.id===id);const p=$('#player');p.src='/media/videos/'+encodeURIComponent(currentVideo.file);p.load();$('#videoState').textContent='Cargando evidencia…';const d=await getJSON('/api/progress/'+id);p.onloadedmetadata=()=>{if(d.position>5&&d.position<p.duration-3)p.currentTime=d.position}}
async function save(force=false){if(!currentVideo||!$('#player').duration)return;const p=$('#player'),now=Date.now();if(!force&&now-lastSave<5000)return;lastSave=now;const duration=p.duration,position=p.currentTime,completed=position/duration>=.95;await getJSON('/api/progress/'+currentVideo.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({position,duration,completed})});refresh()}
$('#player').addEventListener('timeupdate',()=>{const p=$('#player');if(!p.duration)return;const n=Math.round(p.currentTime/p.duration*100);$('#videoBar').style.width=n+'%';$('#videoPct').textContent=n+'%';$('#videoState').textContent=n>=95?'✅ VIDEO COMPLETADO · evidencia observada':'▶ EN PROGRESO · evidencia observada';$('#truthVideo').textContent=n>=95?'VERIFIED':'PENDING';save(false)});$('#player').addEventListener('pause',()=>save(true));$('#player').addEventListener('ended',()=>save(true));$('#sync').addEventListener('click',refresh);document.addEventListener('DOMContentLoaded',()=>{const b=document.getElementById('certBtn');if(b)b.addEventListener('click',issueCert)});function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}load().catch(e=>$('#videoState').textContent='Error: '+e.message);
